const rankerDb = [
  { name: "SkyWalker_99", score: "20B" },
  { name: "Neo_CoderX", score: "19.8B" },
  { name: "PixelNinja77", score: "19.2B" },
  { name: "EchoPhantom_21", score: "19B" },
  { name: "CyberWolf_88", score: "18.4B" },
  { name: "QuantumTigerX", score: "18B" },
  { name: "LunaByte_404", score: "17.6B" },
  { name: "ShadowHawk_09", score: "17.2B" },
  { name: "AlphaZero_777", score: "16.9B" },
  { name: "OmegaFox_13", score: "15B" },
  { name: "ByteKnight_22", score: "14.6B" },
  { name: "HyperNova_01", score: "14.2B" },
  { name: "NeonVortex_66", score: "13.8B" },
  { name: "DarkStorm_333", score: "13B" },
  { name: "SolarFlare_10", score: "12.9B" },
  { name: "InfinityLoopX", score: "12.6B" },
  { name: "StellarEcho_55", score: "12.5B" },
  { name: "TechWiz_90", score: "12B" },
  { name: "VoidRider_07", score: "11.9B" },
  { name: "AstroGamer_12", score: "11B" },
  { name: "ByteCrusherX", score: "10.8B" },
  { name: "CyberDragon_42", score: "10.4B" },
  { name: "CodePhantom_69", score: "10.3B" },
  { name: "HorizonFalcon_23", score: "10.1B" },
  { name: "StealthCobra_88", score: "9.9B" },
  { name: "VortexHunter_77", score: "9.5B" },
  { name: "GlitchX_909", score: "9.3B" },
  { name: "TitanByte_555", score: "9B" },
  { name: "NovaRanger_20", score: "8.9B" },
  { name: "EchoShadow_303", score: "8.7B" }
];

export default rankerDb;